package vistas;

@SuppressWarnings({"serial", "this-escape"})
public class vistaApagarMonitor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaApagarMonitor.class.getName());
    private IControladorMonitor monitor;
    
    public vistaApagarMonitor(IControladorMonitor monitor) {
        initComponents();  
        this.monitor = monitor;
    
        jButton2.addActionListener(e -> {
            jButton2.setEnabled(false); // evitar doble click
            new Thread(() -> {
                monitor.cerrarConexion();
                javax.swing.SwingUtilities.invokeLater(() -> dispose());
            }).start();
        });
    
        // por si cierran con la X sin presionar Apagar
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                jButton2.setEnabled(false); // evitar doble click si aprietan X y botón
                new Thread(() -> {
                    monitor.cerrarConexion();
                    javax.swing.SwingUtilities.invokeLater(() -> dispose());
                }).start();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setBackground(new java.awt.Color(245, 240, 233));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Servidor");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(245, 240, 233));

        jButton2.setBackground(new java.awt.Color(91, 136, 178));
        jButton2.setForeground(new java.awt.Color(245, 240, 233));
        jButton2.setText("Apagar");
        jPanel3.add(jButton2);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    
}
