/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import monitor.Monitor;
import monitor.GestorConfiguracion;


/**
 *
 * @author emila
 */
@SuppressWarnings({"serial", "this-escape"})
public class vistaInicioMonitor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaInicioMonitor.class.getName());
    private Monitor monitor;

    /**
     * Creates new form vistaInicioMonitor
     */
    public vistaInicioMonitor() {
        initComponents();
        monitor = new Monitor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelEncriptacion = new javax.swing.JLabel();
        jComboBoxEncriptacion = new javax.swing.JComboBox<>();
        jLabelPersistencia = new javax.swing.JLabel();
        jComboBoxPersistencia = new javax.swing.JComboBox<>();
        jButtonIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monitor");
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        setLocationRelativeTo(null);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setBackground(new java.awt.Color(245, 240, 233));
        jPanel2.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(10, 20, 10, 20);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 32));
        jLabelTitulo.setText("Monitor");
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.anchor = java.awt.GridBagConstraints.CENTER;
        jPanel2.add(jLabelTitulo, gbc);

        jLabelEncriptacion.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabelEncriptacion.setText("Método de encriptación:");
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.anchor = java.awt.GridBagConstraints.WEST;
        gbc.weightx = 0.3;
        jPanel2.add(jLabelEncriptacion, gbc);

        jComboBoxEncriptacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"AES", "DES", "Blowfish"}));
        jComboBoxEncriptacion.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jComboBoxEncriptacion.setPreferredSize(new java.awt.Dimension(150, 30));
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = java.awt.GridBagConstraints.EAST;
        gbc.weightx = 0.7;
        jPanel2.add(jComboBoxEncriptacion, gbc);

        jLabelPersistencia.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabelPersistencia.setText("Método de persistencia:");
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 1;
        gbc.anchor = java.awt.GridBagConstraints.WEST;
        gbc.weightx = 0.3;
        jPanel2.add(jLabelPersistencia, gbc);

        jComboBoxPersistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"XML", "TXT", "JSON"}));
        jComboBoxPersistencia.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jComboBoxPersistencia.setPreferredSize(new java.awt.Dimension(150, 30));
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = java.awt.GridBagConstraints.EAST;
        gbc.weightx = 0.7;
        jPanel2.add(jComboBoxPersistencia, gbc);

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(245, 240, 233));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButtonIniciar.setBackground(new java.awt.Color(91, 136, 178));
        jButtonIniciar.setForeground(new java.awt.Color(245, 240, 233));
        jButtonIniciar.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.setMaximumSize(new java.awt.Dimension(120, 40));
        jButtonIniciar.setPreferredSize(new java.awt.Dimension(120, 40));
        jButtonIniciar.addActionListener(this::jButtonIniciarActionPerformed);
        jPanel3.add(jButtonIniciar, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Replica el archivo de persistencia más reciente entre el servidor principal (1234)
     * y el secundario (1235) hacia el otro, para que ambos arranquen con el mismo estado.
     * El más reciente (por fecha de modificación) gana, de modo que no se pierden datos
     * aunque en la sesión anterior haya ocurrido un failover.
     */
    private void sincronizarArchivoPersistencia(String persistencia) {
        String ext = switch (persistencia) {
            case "XML" -> "xml";
            case "JSON" -> "json";
            default -> "txt";
        };
        java.io.File f1234 = new java.io.File("estadoSistema_Servidor1." + ext);
        java.io.File f1235 = new java.io.File("estadoSistema_Servidor2." + ext);
        try {
            if (f1234.exists() && f1235.exists()) {
                if (f1234.lastModified() >= f1235.lastModified())
                    java.nio.file.Files.copy(f1234.toPath(), f1235.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
                else
                    java.nio.file.Files.copy(f1235.toPath(), f1234.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
            } else if (f1234.exists()) {
                java.nio.file.Files.copy(f1234.toPath(), f1235.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
            } else if (f1235.exists()) {
                java.nio.file.Files.copy(f1235.toPath(), f1234.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
            }
            // Si ninguno existe, ambos arrancan vacíos (también es un estado consistente).
        } catch (java.io.IOException ex) {
            // Si la copia falla, el secundario arrancará con su propio archivo; no es crítico.
            logger.log(java.util.logging.Level.WARNING, "No se pudo sincronizar el archivo de persistencia", ex);
        }
    }

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {
        jButtonIniciar.setEnabled(false);

        new Thread(() -> {
            try {
                String cifrado = (String) jComboBoxEncriptacion.getSelectedItem();
                String persistencia = (String) jComboBoxPersistencia.getSelectedItem();

                GestorConfiguracion config = new GestorConfiguracion();
                int puertoPrincipal = config.getPuertoPrincipal();
                int puertoSecundario = config.getPuertoSecundario();

                monitor.setCifrado(cifrado);
                monitor.iniciaLlave(cifrado);

                String classpath = System.getProperty("java.class.path");
                String javaHome = System.getProperty("java.home");
                String javaExe = javaHome + java.io.File.separator + "bin" + java.io.File.separator + "java";

                sincronizarArchivoPersistencia(persistencia);

                ProcessBuilder pb1 = new ProcessBuilder(
                    javaExe, "-cp", classpath,
                    "servidor.Servidor",
                    String.valueOf(puertoPrincipal), "PRINCIPAL",
                    monitor.getCifrado(),
                    monitor.getLlaveString(),
                    persistencia
                );
                pb1.inheritIO();
                Process procesoPrincipal = pb1.start();

                ProcessBuilder pb2 = new ProcessBuilder(
                    javaExe, "-cp", classpath,
                    "servidor.Servidor",
                    String.valueOf(puertoSecundario), "SECUNDARIO",
                    monitor.getCifrado(),
                    monitor.getLlaveString(),
                    persistencia
                );
                pb2.inheritIO();
                Process procesoSecundario = pb2.start();

                // Esperar a que los servidores levanten
                Thread.sleep(2000);

                // Conectar el monitor a los servidores y empezar a escuchar clientes
                monitor.agregarServidor(puertoPrincipal, 1);
                monitor.agregarServidor(puertoSecundario, 2);
                monitor.setPuertoActivo(puertoPrincipal);
                monitor.iniciaConexionServidor(puertoPrincipal);
                monitor.iniciaConexionApliaciones();
                monitor.establecerProcesos(procesoPrincipal, procesoSecundario);

                monitor.setTipoPersistencia(persistencia);

                javax.swing.SwingUtilities.invokeLater(() -> {
                    vistaApagarMonitor ventana = new vistaApagarMonitor(monitor);
                    ventana.setVisible(true);
                    dispose();
                });
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al iniciar los servidores: " + e.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                jButtonIniciar.setEnabled(true);
            }
        }).start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vistaInicioMonitor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelEncriptacion;
    private javax.swing.JComboBox<String> jComboBoxEncriptacion;
    private javax.swing.JLabel jLabelPersistencia;
    private javax.swing.JComboBox<String> jComboBoxPersistencia;
    private javax.swing.JButton jButtonIniciar;
    // End of variables declaration//GEN-END:variables
}
